function [SEK,SBK,count_sp_SBK,check_b_d,max_d_intensity,min_b_intensity]=find_SEK_SBK(bwimg,check_b_d,max_d_intensity,min_b_intensity,rows,col)
m=13;
SEK=zeros(rows,col);
SBK=zeros(rows,col);
count_sp_SBK=zeros(rows,col);
for i = 3 : size(bwimg,1) - 2
      for j = 3 : size(bwimg,2) - 2
          b=bwimg(i,j)+m;
          d=bwimg(i,j)-m;
          P(1)=bwimg(i-2,j);P(2)=bwimg(i-2,j+1);P(3)=bwimg(i-1,j+2);P(4)=bwimg(i,j+2);
          P(5)=bwimg(i+1,j+2);P(6)=bwimg(i+2,j+1);P(7)=bwimg(i+2,j);P(8)=bwimg(i+2,j-1);
          P(9)=bwimg(i+1,j-2);P(10)=bwimg(i,j-2);P(11)=bwimg(i-1,j-2);P(12)=bwimg(i-2,j-1);
          pi(1)=bwimg(i-1,j);pi(2)=bwimg(i-1,j+1);pi(3)=bwimg(i,j+1);pi(4)=bwimg(i+1,j+1);
          pi(5)=bwimg(i+1,j);pi(6)=bwimg(i+1,j-1);pi(7)=bwimg(i,j-1);pi(8)=bwimg(i-1,j-1);
          flag=0;max_value_b=0;max_value_d=0;count_bp=0;count_dp=0;count_sp=0;minb=255;maxd=0;
          sp_index=zeros(1,12);dp_index=zeros(1,12);bp_index=zeros(1,12);
          for k = 1 : 12
              if(P(k)<b&&P(k)>d)
                    if(k<=6)    
                      if(P(k+6)<b&&P(k+6)>d)
                        flag=1;
                        break;
                      end
                    end
                    if(k==1)
                        if(pi(1)>=b||pi(1)<=d)
                            flag=1;
                            break;
                        end
                    elseif(k==2||k==3)
                        if(pi(2)>=b||pi(2)<=d)
                            flag=1;
                            break;
                        end
                    elseif(k==4)
                        if(pi(3)>=b||pi(3)<=d)
                            flag=1;
                            break;
                        end
                    elseif(k==5||k==6)
                        if(pi(4)>=b||pi(4)<=d)
                            flag=1;
                            break;
                        end
                    elseif(k==7)
                        if(pi(5)>=b||pi(5)<=d)
                            flag=1;
                            break;
                        end
                    elseif(k==8||k==9)
                        if(pi(6)>=b||pi(6)<=d)
                            flag=1;
                            break;
                        end
                    elseif(k==10)
                        if(pi(7)>=b||pi(7)<=d)
                            flag=1;
                            break;
                        end
                    else
                        if(pi(8)>=b||pi(8)<=d)
                            flag=1;
                            break;
                        end
                    end
                    count_sp=count_sp+1;
                    if(count_sp==1)
                        sp_index(count_sp)=k;
                    else
                        sp_index(count_sp)=k-sum(sp_index);
                    end
              elseif(P(k)>=b)
                  count_bp=count_bp+1;
                  if(count_bp==1)
                        bp_index(count_bp)=k;
                  else
                        bp_index(count_bp)=k-sum(bp_index);
                  end
                  x=P(k)-bwimg(i,j);
                  if(x>max_value_b)
                      max_value_b=x;
                  end
                  x=P(k);
                  if(x<minb)
                      minb=x;
                  end
              else
                  count_dp=count_dp+1;
                  if(count_dp==1)
                        dp_index(count_dp)=k;
                    else
                        dp_index(count_dp)=k-sum(dp_index);
                  end
                  x=bwimg(i,j)-P(k);
                  if(x>max_value_d)
                      max_value_d=x;
                  end
                  x=P(k);
                  if(x>maxd)
                      maxd=x;
                  end
              end
          end
          if(count_dp<6&&count_bp<6)
              flag=1;
          end
          if(count_sp<1||count_sp==6)
              flag=1;
          end
          if(flag==0)
            if(count_sp==3)
                if(count_bp==9||count_dp==9)
                    if(sp_index(3)==1&&(sp_index(2)==1||sp_index(2)==10))%Condition for a similar 3 element contigous segment
                        flag=1;
                        if(count_bp==9)
                            SEK(i,j)=max_value_b;
                            check_b_d(i,j)=-1;
                            min_b_intensity(i,j)=minb;
                        else
                            SEK(i,j)=max_value_d;
                            check_b_d(i,j)=1;
                            max_d_intensity(i,j)=maxd;
                        end
                    elseif(sp_index(2)~=1&&sp_index(3)~=1)%Deleting Conditions for SBK
                        if(sp_index(1)~=1)
                            flag=1;
                        else
                            if(sp_index(1)+sp_index(2)+sp_index(3)~=12)
                                flag=1;
                            end
                        end
                    end
                else
                     flag=1;                                   
                end
            elseif(count_sp==1)
                flag=1;
                if(count_bp==11)
                    SEK(i,j)=max_value_b;
                    check_b_d(i,j)=-1;
                    min_b_intensity(i,j)=minb;
                elseif(count_dp==11)
                    SEK(i,j)=max_value_d;
                    check_b_d(i,j)=1;
                    max_d_intensity(i,j)=maxd;
                end
            elseif(count_sp==2)
              if(sp_index(2)==1||(sp_index(1)==1&&sp_index(2)==11))
                  flag=1;
                if(count_bp>count_dp)
                    SEK(i,j)=max_value_b;
                    check_b_d(i,j)=-1;
                    min_b_intensity(i,j)=minb;
                else
                    SEK(i,j)=max_value_d;
                    check_b_d(i,j)=1;
                    max_d_intensity(i,j)=maxd;
                end
              else
                  if(count_dp>0&&count_bp>0)
                      flag=1;
                  end
              end   
            elseif(count_sp==4||count_sp==5)
              count_not_one=0;
              for o = 2 : count_sp
                if(sp_index(o)~=1)
                  count_not_one=count_not_one+1;
                end
              end
              if(count_not_one>=3)%Deleting conditions for SBK
                flag=1;
              elseif(count_not_one==2&&sp_index(1)==1)
                if(count_sp==3&&sp_index(1)+sp_index(2)+sp_index(3)~=12)%Deleting conditions for SBK
                  flag=1;
                elseif(count_sp==4&&sp_index(1)+sp_index(2)+sp_index(3)+sp_index(4)~=12)%Deleting conditions for SBK
                  flag=1;
                else
                    if(count_dp>0&&count_bp>0)
                        flag=1;
                    end
                end
              elseif(count_not_one==2&&sp_index(1)~=1)
                  flag=1;
              else
                if(count_dp>0&&count_bp>0)
                    flag=1;
                end
              end
            end
          end
          if(flag==0)
              if(count_dp>0)
                  SBK(i,j)=max_value_d;
                  check_b_d(i,j)=1;
                  max_d_intensity(i,j)=maxd;
                  count_sp_SBK(i,j)=count_sp;
              else
                  SBK(i,j)=max_value_b;
                  check_b_d(i,j)=-1;
                  min_b_intensity(i,j)=minb;
                  count_sp_SBK(i,j)=count_sp;
              end
          end
      end
 end